In [207]:
import pandas as pd

In [208]:
course = pd.read_csv('../data-csv/course.csv', parse_dates=['date_started'])

In [209]:
course['max_score'].dtype # для справочки если есть nan среди int то тип колонки - float

dtype('float64')

In [210]:
user_course_progress = pd.read_csv('../data-csv/user_course_progress.csv')

#### Относительным прогрессом будем называть отношение суммарного числа баллов, которые ученик набрал за курс (колонка progress в таблице user_course_progress), к максимальному количеству баллов, которые ученик в принципе мог набрать за данный курс (колонка max_progress в таблице course).

In [211]:
user_course_progress

      user_id  course_id  progress
0         392          1     31.68
1         217          1     97.53
2         843          1     81.50
3         417          1     15.92
4         605          1    103.31
...       ...        ...       ...
1706      898         10      8.01
1707      201         10      0.71
1708      334         10      1.90
1709      112         10      2.16
1710      255         10      5.99

[1711 rows x 3 columns]

## На курсах какого предмета больше всего учеников, чей относительный прогресс не меньше 0.8?

In [219]:
course_progress = course \
    .merge(user_course_progress, left_on='id', right_on='course_id', suffixes=('_x','_y'), how='inner')

In [232]:
len(course_progress[course_progress['subject'] == 'Химия'])

678

In [235]:
course_progress = course_progress.dropna(subset=['max_score'])

In [236]:
course_progress = course_progress.drop(columns=['id','date_started']) #убираем ненужные колонки

In [237]:
# Каждый предмет содержит в себе несколько курсов, которые могут проходить ребята ОДНОВРЕМЕННО
course_progress['subject'].unique()

<StringArray>
['Химия', 'Физика', 'Математика']
Length: 3, dtype: str

In [238]:
course_progress['relative_progress'] = round(course_progress['progress'] / course_progress['max_score'], 2)

In [239]:
course_progress['relative_progress'].mean().round(2)

np.float64(0.35)

In [240]:
course_mt_80 = course_progress[course_progress['relative_progress'] >= 0.8]

In [180]:
course_mt_80[course_mt_80['subject']=='Химия']

,id,subject,date_started,max_score,user_id,course_id,progress,relative_progress
1,1,Химия,2023-04-04,108.0,217,1,97.53,0.90
4,1,Химия,2023-04-04,108.0,605,1,103.31,0.96
25,1,Химия,2023-04-04,108.0,720,1,105.11,0.97
28,1,Химия,2023-04-04,108.0,679,1,97.80,0.91
29,1,Химия,2023-04-04,108.0,364,1,92.21,0.85
...,...,...,...,...,...,...,...,...
1470,9,Химия,2023-01-16,120.0,101,9,115.36,0.96
1479,9,Химия,2023-01-16,120.0,27,9,115.83,0.97
1491,9,Химия,2023-01-16,120.0,838,9,118.97,0.99
1504,9,Химия,2023-01-16,120.0,520,9,108.40,0.90
1510,9,Химия,2023-01-16,120.0,806,9,107.60,0.90

In [181]:
course_mt_80 = course_mt_80[['subject', 'user_id','course_id']].sort_values('user_id')

In [198]:
course_mt_80.groupby(['subject']).agg({'user_id': 'count'}).sort_values('user_id', ascending=False)

            user_id
subject
Химия           108
Математика       32
Физика           24