In [1]:
import pandas as pd

In [2]:
course = pd.read_csv('../data-csv/course.csv', parse_dates=['date_started'])

In [ ]:
course['max_score'].dtype # для справочки если есть nan среди int то тип колонки - float

dtype('float64')

In [7]:
user_course_progress = pd.read_csv('../data-csv/user_course_progress.csv')

#### Относительным прогрессом будем называть отношение суммарного числа баллов, которые ученик набрал за курс (колонка progress в таблице user_course_progress), к максимальному количеству баллов, которые ученик в принципе мог набрать за данный курс (колонка max_progress в таблице course).

In [8]:
course

   id     subject date_started  max_score
0   1       Химия   2023-04-04      108.0
1   2      Физика   2023-01-31      137.0
2   3    Биология   2023-09-14        NaN
3   4       Химия   2023-03-31      118.0
4   5      Физика   2023-11-30        NaN
5   6       Химия   2023-03-03      102.0
6   7    Биология   2023-11-19        NaN
7   8      Физика   2023-06-08        NaN
8   9       Химия   2023-01-16      120.0
9  10  Математика   2023-02-18      104.0

In [9]:
user_course_progress

      user_id  course_id  progress
0         392          1     31.68
1         217          1     97.53
2         843          1     81.50
3         417          1     15.92
4         605          1    103.31
...       ...        ...       ...
1706      898         10      8.01
1707      201         10      0.71
1708      334         10      1.90
1709      112         10      2.16
1710      255         10      5.99

[1711 rows x 3 columns]

## На курсах какого предмета больше всего учеников, чей относительный прогресс не меньше 0.8?

In [ ]:
course_progress = course \
    .merge(user_course_progress, left_on='id', right_on='course_id', suffixes=('_x','_y'), how='inner') \
    
course_progress[course_progress['subject'] == 'Химия']

(1711, 7)

In [21]:
course_progress = course_progress.drop(columns=['id','date_started']).sort_values('user_id') #убираем ненужные колонки

In [19]:
# Каждый предмет содержит в себе несколько курсов, которые могут проходить ребята ОДНОВРЕМЕННО

In [23]:
course_progress['relative_progress'] = round(course_progress['progress'] / course_progress['max_score'], 2)

In [30]:
course_mt_80 = course_progress[course_progress['relative_progress'] >= 0.8]

In [38]:
course_mt_80 = course_mt_80[['subject', 'user_id','course_id']].sort_values('user_id')

In [41]:
course_mt_80.groupby(['subject']).agg({'user_id': 'count'}).sort_values('user_id', ascending=False)

            user_id
subject
Химия           108
Математика       32
Физика           24